export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_PAGE = 'SET_PAGE';

export const FETCH_TOP_NEWS_STARTED = 'FETCH_TOP_NEWS_STARTED';
export const FETCH_TOP_NEWS_FINISHED = 'FETCH_TOP_NEWS_FINISHED';
export const FETCH_TOP_NEWS_FAILED = 'FETCH_TOP_NEWS_FAILED';