export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_PAGE = 'SET_PAGE';

export const FETCH_TOP_NEWS_STARTED = 'FETCH_TOP_NEWS_STARTED';
export const FETCH_TOP_NEWS_FINISHED = 'FETCH_TOP_NEWS_FINISHED';
export const FETCH_TOP_NEWS_FAILED = 'FETCH_TOP_NEWS_FAILED';

export const FETCH_TOP_NEWS_BY_TERM_STARTED = 'FETCH_TOP_NEWS_BY_TERM_STARTED';
export const FETCH_TOP_NEWS_BY_TERM_FINISHED = 'FETCH_TOP_NEWS_BY_TERM_FINISHED';
export const FETCH_TOP_NEWS_BY_TERM_FAILED = 'FETCH_TOP_NEWS_BY_TERM_FAILED';

export const SELECT_ARTICLE = 'SELECT_ARTICLE';

export const FETCH_NEWS_BY_CATEGORY_STARTED = 'FETCH_NEWS_BY_CATEGORY_STARTED';
export const FETCH_NEWS_BY_CATEGORY_FINISHED = 'FETCH_NEWS_BY_CATEGORY_FINISHED';
export const FETCH_NEWS_BY_CATEGORY_FAILED = 'FETCH_NEWS_BY_CATEGORY_FAILED';